.. note::

    To focus our efforts onto a manageable number of packages, this package is
    currently *not* maintained. Security fixes and submitted bug fixes will
    still be released, but no new features should be expected.

    If you want to help co-maintaining this package, tell us in a GitHub issue
    or in #symfony_cmf of the `Symfony devs slack`_.

    This bundle might have outdated documentation and there is no support and
    bugs will usually not be fixed.

.. _`Symfony devs slack`: https://slackinvite.me/to/symfony-devs
